export const ROUTE_ABOUT = '/about'
export const ROUTE_CONTACT = '/contact'
export const ROUTE_CONVERT = '/'
export const ROUTE_PRIVACY = '/privacy'
export const ROUTE_SECURITY = '/security'
export const ROUTE_TERMS = '/terms'
