name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubicloud
    steps:
      - uses: "actions/checkout@v4"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache:        "yarn"
      - name: Install packages
        run: "yarn install"
      - name: Build the application
        run: "yarn build"
