name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache:        "yarn"
      - name: Install packages
        run: "yarn install"
      - name: Build the application
        run: "yarn build"
