name: Publish to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish_to_dockerhub:
    # Previously tried to use on-push-tag to trigger this, but semantic-release
    # doesn't trigger it. See https://github.com/actions/runner/issues/1007
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get the version
        run:  echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder:    ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/string-is:buildcache
          cache-to:   type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/string-is:buildcache,mode=max
          context:    ./
          file:       ./Dockerfile
          platforms:  linux/arm64, linux/amd64
          push:       true
          tags:       ${{ secrets.DOCKER_HUB_USERNAME }}/string-is:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/string-is:${{ env.RELEASE_VERSION }}
