name: eslint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache:        "yarn"
      - name: Install packages
        run: "yarn install"
      - name: Run eslint
        run: "yarn eslint"
