name: jest

on:
  pull_request:
  push: { branches: ["develop", "main"] }

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache:        "yarn"
      - name: Install packages
        run:  yarn install
      - name: Run jest
        run:  yarn jest --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
