name: jest

on: [pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Install packages
        run: "npm install"
      - name: Run jest
        run: "yarn jest"
