name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache:        "yarn"
      - name: Install packages
        run: yarn install
      - name: Release
        env:
          # Use this so that we can trigger the Docker Hub action on tag after release.
          # The regular GITHUB_TOKEN doesn't trigger it.
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release
